### ISSUE TITLE
side_info in sim_eval

### ISSUE THREAD

**Issue by AlexandreWadoux** [l-ramirez-lopez/resemble#10]
with the updated version of the package the sim_eval function returns an error 

`Error in sim_eval(d = mdXr, side_info = xrData$"Organic carbon") : 
  side_inf must be a matrix`

`xrData$"Organic carbon"` is a numeric vector, not a matrix. This is of course solved by using `as.matrix(xrData$'Organic carbon')` but maybe a numeric vector could be accepted.

**Comment by l-ramirez-lopez** [comment]
not coercing the vector to a matrix is intentional. The reason is that  some functions that call sim_eval numerous times (e.g. ortho_diss) and we want to avoid class checks
