### ISSUE TITLE
modify some code from your script

### ISSUE THREAD

**Issue by guokai8** [l-ramirez-lopez/resemble#25]
Hi,
I am Kai. These days I am working on a small package called o2plsda, and I tried to modified some C++ code from your resemble for OPLS-DA. I just wonder if it is OK for me to modify your code and use it in my package (Since I don't need some function in your code). I will mention the code were from your github. Please let me know. 
And if you are OK for this and could you provide the pseudo code for your OPLS algorithm since the code are slightly difference from the book (Comprehensive Chemometrics Chemical and Biochemical Data Analysis, Page:208) I read.
Thanks!
Kai

**Comment by l-ramirez-lopez** [comment]
Hi Kai,
yes of course, feel free to reproduce the chunks of code you need. 
The algorithm I implemented is NIPALS. A pseudo-code of NIPALS can be found in Geladi, P., & Kowalski, B. R. (1986). Partial least-squares regression: a tutorial. Analytica chimica acta, 185, 1-17. (check page 7). You can access the paper here: http://home.mit.bme.hu/~horvath/IDA/1-s2.0-0003267086800289-main.pdf 

Let me know if you have any questions regarding my code
Cheers
Leo

**Comment by guokai8** [comment]
Hi Leo,
Thanks! I will let you know if I have further questions. 
Cheers,
Kai
